### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\DIS~1.DES\\AppData\\Local\\Temp\\tmppoz7de8s'

### ISSUE THREAD

**Issue by choesy** [OxWearables/stepcount#16] opened 2023-03-03 09:22 UTC
I get a permission error when running:
```text
stepcount .\data.csv
```
on windows 10.

The csv file is in the format of:

```csv
time,x,y,z
2020-05-14 17:57:53.359,-10.2578125,2.03769534,-1.85380855
2020-05-14 17:57:53.379,-10.305397727272728,1.8335404909090909,-1.5747514181818183
2020-05-14 17:57:53.399,-10.583806818181818,0.8554687327272728,-1.8620383636363635
2020-05-14 17:57:53.419,-10.034801136363637,-0.491788,-1.5311612454545451
2020-05-14 17:57:53.439,-9.323153409090908,-0.9483753545454544,-1.0940162999999998
2020-05-14 17:57:53.459,-8.506392045454545,-0.5928178490909091,-0.7536399181818182
2020-05-14 17:57:53.479,-8.5546875,-0.15795898,0.18908691
2020-05-14 17:57:53.499,-8.9140625,0.08618164,-0.05505371
2020-05-14 17:57:53.519,-9.03125,-0.11968994,-0.60791016
2020-05-14 17:57:53.539,-9.5,-1.2490233999999998,-0.15319824
2020-05-14 17:57:53.559,-9.921875,-0.61279297,1.2783203
```
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\DIS~1.DES\\AppData\\Local\\Temp\\tmppoz7de8s'

**Comment by chanshing** [comment] 2023-03-03 09:27
Do you have access permission to `C:\Users\DIS~1.DES\AppData\Local\Temp` ?

**Comment by choesy** [comment] 2023-03-03 10:09
I fixed the error by editing the file memmap_utils in my virtual enviromet. I changed
```python
with tempfile.NamedTemporaryFile() as f:
        y = np.memmap(f.name, mode="w+", dtype=dtype, shape=shape)
```
to 

```python
with tempfile.NamedTemporaryFile(delete=False) as f:
        y = np.memmap(f.name, mode="w+", dtype=dtype, shape=shape)
```
The data now loads, I printed it out in stepcount.py

But another problem occurs ( you will also see printed out data):
```text
Getting stationary points... Done! (0.01s)
C:\Users\dis.DESKTOP-VQQL5UB\Desktop\UKB_steps_mortality\.stepvenv\Lib\site-packages\actipy\processing.py:251: UserWarning: Skipping calibration: Insufficient stationary samples
  warnings.warn(f"Skipping calibration: Insufficient stationary samples")
Gravity calibration... Done! (0.01s)
Nonwear detection... Done! (0.01s)
Resampling... Done! (0.01s)
Running step counter...
                                 x          y         z
time
2020-05-14 17:57:53.359 -10.257812   2.037695 -1.853809
2020-05-14 17:57:53.379 -10.305398   1.833540 -1.574751
2020-05-14 17:57:53.399 -10.583807   0.855469 -1.862038
2020-05-14 17:57:53.419 -10.034801  -0.491788 -1.531161
2020-05-14 17:57:53.439  -9.323153  -0.948375 -1.094016
...                            ...        ...       ...
2020-05-14 18:03:15.199 -13.417969  -8.163281  4.825391
2020-05-14 18:03:15.219 -10.488636  -7.744318  5.806818
2020-05-14 18:03:15.239 -10.286719  -9.053906  6.427344
2020-05-14 18:03:15.259  -9.989347 -10.226562  6.129616
2020-05-14 18:03:15.279  -8.415625 -10.826562  4.620313

[16097 rows x 3 columns]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\dis.DESKTOP-VQQL5UB\Desktop\UKB_steps_mortality\.stepvenv\Scripts\stepcount.exe\__main__.py", line 7, in <module>
  File "C:\Users\dis.DESKTOP-VQQL5UB\Desktop\UKB_steps_mortality\.stepvenv\Lib\site-packages\stepcount\stepcount.py", line 57, in main
    Y = model.predict_from_frame(data)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dis.DESKTOP-VQQL5UB\Desktop\UKB_steps_mortality\.stepvenv\Lib\site-packages\stepcount\models.py", line 201, in predict_from_frame
    Y = self.predict(X, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dis.DESKTOP-VQQL5UB\Desktop\UKB_steps_mortality\.stepvenv\Lib\site-packages\stepcount\models.py", line          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dis.DESKTOP-VQQL5UB\Desktop\UKB_steps_mortality\.stepvenv\Lib\site-packages\stepcount\models.py", line 305, in predict
    W = self.hmms.predict(W, groups=groups)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dis.DESKTOP-VQQL5UB\Desktop\UKB_steps_mortality\.stepvenv\Lib\site-packages\stepcount\hmm_utils.py", line 48, in predict
    return self.hmmlearn_fit_predict(Y, groups=groups, method='predict')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dis.DESKTOP-VQQL5UB\Desktop\UKB_steps_mortality\.stepvenv\Lib\site-packages\stepcount\hmm_utils.py", line 98, in hmmlearn_fit_predict
    _hmm, _score, _Y_pred = hmmlearn_fit_predict(Y[groups == g], groups=None, **hmm_params)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dis.DESKTOP-VQQL5UB\Desktop\UKB_steps_mortality\.stepvenv\Lib\site-packages\stepcount\hmm_utils.py", line 190, in hmmlearn_fit_predict
    hmm.fit(Y_train, lengths_from_groups(groups_train))
  File "C:\Users\dis.DESKTOP-VQQL5UB\Desktop\UKB_steps_mortality\.stepvenv\Lib\site-packages\hmmlearn\hmm.py", line 327, in <lambda>
    lambda *args, **kwargs: func(*args, **kwargs))
                            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dis.DESKTOP-VQQL5UB\Desktop\UKB_steps_mortality\.stepvenv\Lib\site-packages\hmmlearn\base.py", line 495, in fit
    self._check()
  File "C:\Users\dis.DESKTOP-VQQL5UB\Desktop\UKB_steps_mortality\.stepvenv\Lib\site-packages\hmmlearn\hmm.py", line 457, in _check
    raise ValueError(
ValueError: emissionprob_ must have shape (n_components, n_features)
```

**Comment by chanshing** [comment] 2023-03-03 11:21
Which version of stepcount are you using?

**Comment by choesy** [comment] 2023-03-03 11:23
Installed with pip, version is 1.3.0.

**Comment by choesy** [comment] 2023-03-03 11:36
I directly downloaded the repository and installed the stepcount package version 2.0.5 . Now I think the error is fixed. But I get another error now, also I am using python 3.9.10 now. On what python version it is tested? :
```text
UserWarning: Skipping calibration: Insufficient stationary samples
  warnings.warn(f"Skipping calibration: Insufficient stationary samples")
Gravity calibration... Done! (0.00s)
C:\Users\dis.DESKTOP-VQQL5UB\.pyenv\pyenv-win\versions\3.9.10\lib\site-packages\actipy\processing.py:125: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

        >>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

        >>> .groupby(..., group_keys=True)
  stationary_len = (group.groupby(group, dropna=True)
Traceback (most recent call last):
  File "C:\Users\dis.DESKTOP-VQQL5UB\.pyenv\pyenv-win\versions\3.9.10\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\dis.DESKTOP-VQQL5UB\.pyenv\pyenv-win\versions\3.9.10\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dis.DESKTOP-VQQL5UB\.pyenv\pyenv-win\versions\3.9.10\Scripts\stepcount.exe\__main__.py", line 7, in <module>
  File "C:\Users\dis.DESKTOP-VQQL5UB\.pyenv\pyenv-win\versions\3.9.10\lib\site-packages\stepcount\stepcount.py", line 45, in main
    data, info = read(args.filepath, resample_hz)
  File "C:\Users\dis.DESKTOP-VQQL5UB\.pyenv\pyenv-win\versions\3.9.10\lib\site-packages\stepcount\stepcount.py", line 218, in read
    data, info = actipy.process(
  File "C:\Users\dis.DESKTOP-VQQL5UB\.pyenv\pyenv-win\versions\3.9.10\lib\site-packages\actipy\reader.py", line 121, in process
    data, info_nonwear = P.detect_nonwear(data, stationary_indicator=stationary_indicator)
  File "C:\Users\dis.DESKTOP-VQQL5UB\.pyenv\pyenv-win\versions\3.9.10\lib\site-packages\actipy\processing.py", line 127, in detect_nonwear
    nonwear_len = stationary_len[stationary_len > pd.Timedelta(patience)]
  File "C:\Users\dis.DESKTOP-VQQL5UB\.pyenv\pyenv-win\versions\3.9.10\lib\site-packages\pandas\core\ops\common.py", line 72, in new_method
    return method(self, other)
  File "C:\Users\dis.DESKTOP-VQQL5UB\.pyenv\pyenv-win\versions\3.9.10\lib\site-packages\pandas\core\arraylike.py", line 58, in __gt__
    return self._cmp_method(other, operator.gt)
  File "C:\Users\dis.DESKTOP-VQQL5UB\.pyenv\pyenv-win\versions\3.9.10\lib\site-packages\pandas\core\series.py", line 6243, in _cmp_method
    res_values = ops.comparison_op(lvalues, rvalues, op)
  File "C:\Users\dis.DESKTOP-VQQL5UB\.pyenv\pyenv-win\versions\3.9.10\lib\site-packages\pandas\core\ops\array_ops.py", line 273, in comparison_op
    res_values = op(lvalues, rvalues)
TypeError: '>' not supported between instances of 'numpy.ndarray' and 'Timedelta'
```

**Comment by chanshing** [comment] 2023-03-03 12:03
Can you try a fresh install in a new virtual environment?

**Comment by choesy** [comment] 2023-03-03 13:18
I found out, that on "sample.cwa" it works without a problem. I guess there is a problem with my "data.csv". But I don't know what. There are no missing values and the format is correct.

**Comment by chanshing** [comment] 2023-03-03 13:38
Ok, I think it might be a problem on our end then. The file you've shown seems to be very short (5 mins?), which we haven't tested for. I'll investigate and get back to you!

**Comment by choesy** [comment] 2023-03-03 13:45
Ok, thank you 😁

**Comment by chanshing** [comment] 2023-03-06 12:49
I am not able to reproduce this error using a shorter file (~5min). What method did you use to install the package?

**Comment by choesy** [comment] 2023-03-06 15:25
I used normal "pip install stepcount" inside venv.

**Comment by choesy** [comment] 2023-03-08 12:15
UPDATE:
I found the source of the problem. 
Because my csv file is soo small, it does not find non-wearing activity in the function detect_nonwear(...) of actipy.processing module. 
```python

  info = {}

  if stationary_indicator is None:
      stationary_indicator = get_stationary_indicator(data)

  group = ((stationary_indicator != stationary_indicator.shift(1))
           .cumsum()
           .where(stationary_indicator))
  stationary_len = (group.groupby(group, dropna=True)
                         .apply(lambda g: g.index[-1] - g.index[0]))
  nonwear_len = stationary_len[stationary_len > pd.Timedelta(patience)]

  nonwear_time = nonwear_len.sum().total_seconds()
  wear_time, _ = get_wear_time(data.index.to_series())
  info['WearTime(days)'] = (wear_time - nonwear_time) / (60 * 60 * 24)  # update wear time
  info['NonwearTime(days)'] = nonwear_time / (60 * 60 * 24)
  info['NumNonwearEpisodes'] = len(nonwear_len)

  # Flag nonwear
  nonwear_indicator = group.isin(nonwear_len.index)
  if drop:
      data = data[~nonwear_indicator]
  else:
      data = data.mask(nonwear_indicator)

  return data, info
```
the stationary_len is empty.
the comparison with empty Series happens in the line.
```python
nonwear_len = stationary_len[stationary_len > pd.Timedelta(patience)]
```
I don't know how to fix this, but it is the source of a problem.

**Comment by chanshing** [comment] 2023-03-21 19:55
@choesy Oh nice! Thanks for debugging this, and sorry for my slow response -- It's been a busy week.
I'll try to get a patch soon.

**Comment by chanshing** [comment] 2023-03-21 20:53
This is fixed now!

**Closed by chanshing** 2023-03-21 20:53 UTC
